name: flortmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_analytics: ^11.4.6
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^0.8.7+4
  flutter_spinkit: ^5.1.0
  firebase_crashlytics: ^4.3.6
  in_app_purchase: ^3.2.3
  record: ^4.4.4
  audioplayers: ^3.0.1
  path: any
  file_selector: ^1.0.3
  permission_handler: ^10.4.0
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.0
  flutter_localizations:
    sdk: flutter
  intl: ">=0.18.1 <0.21.0"
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutterfire_cli: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/badges/

dependency_overrides:
  json_annotation: ^2.0.0
