// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnsrlSzzPfnZEUzoCpNp4svEuTwG1AmY4',
    appId: '1:379793521961:web:173e8c26481eea39a28b38',
    messagingSenderId: '379793521961',
    projectId: 'flortmate',
    authDomain: 'flortmate.firebaseapp.com',
    storageBucket: 'flortmate.firebasestorage.app',
    measurementId: 'G-WWSQGLE4BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPq6PLxaCMEgo8p1s4XK4gJBx6Zq9uPt4',
    appId: '1:379793521961:android:9d58d0a3f1b56b55a28b38',
    messagingSenderId: '379793521961',
    projectId: 'flortmate',
    storageBucket: 'flortmate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlpSI4gi4mt4f4ulzHxqzodgMakbNM4Y',
    appId: '1:379793521961:ios:2b69edfb7a741d07a28b38',
    messagingSenderId: '379793521961',
    projectId: 'flortmate',
    storageBucket: 'flortmate.firebasestorage.app',
    iosBundleId: 'com.example.flortmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlpSI4gi4mt4f4ulzHxqzodgMakbNM4Y',
    appId: '1:379793521961:ios:2b69edfb7a741d07a28b38',
    messagingSenderId: '379793521961',
    projectId: 'flortmate',
    storageBucket: 'flortmate.firebasestorage.app',
    iosBundleId: 'com.example.flortmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnsrlSzzPfnZEUzoCpNp4svEuTwG1AmY4',
    appId: '1:379793521961:web:14dad169f1d1e8fda28b38',
    messagingSenderId: '379793521961',
    projectId: 'flortmate',
    authDomain: 'flortmate.firebaseapp.com',
    storageBucket: 'flortmate.firebasestorage.app',
    measurementId: 'G-JGZ35CCJZX',
  );

}
